### ISSUE TITLE
xatkit-install-linux doesn't run the export command

### ISSUE THREAD

**Issue by gdaniel** [xatkit-bot-platform/xatkit-dev#10]
It needs to be run manually, we need to fix that.

Found by @jcabot

**Comment by abelgomez** [comment]
The environment of the install script is different that the environment of the parent shell used to run de install script. The way to fix it is to run the command in the same environment using the `.` command (note: `source` is equivalent to `.`, maybe it's preferrable to use `source` to avoid confusion). Addressed in #11 (mostly by updating the installation instructions)

#11 also addresses the discouraged use of `$(pwd)` in favor of `$(dirname $(realpath -- $BASH_SOURCE))`, which is more robust.

**Comment by gdaniel** [comment]
fixed in #11
