### ISSUE TITLE
Provide an example unit file to start Xatkit as a systemd service

### ISSUE THREAD

**Issue by abelgomez** [xatkit-bot-platform/xatkit-dev#12]
Suggestion: it may be a good idea to document somewhere how a beginner may deploy the example _GreetingsBot_ as a systemd service to run it automatically at system boot (thus covering a vast majority of the most widespread linux distributions).

Assuming the user cloned xatkit-dev in `/home/user/xatkit-dev`. The steps would be:

1. Create a `/etc/systemd/system/xatkit.service` file, for example using nano:
```
sudo nano /etc/systemd/system/xatkit.service
```
2. Copy the example unit file below to the `/etc/systemd/system/xatkit.service` file. It would be preferrable if the user copies the contents of the `build` directory to somewhere outside his/her home, such as `/opt/xatkit`. In that case, the XATKIT variable should be updated to the proper location:
```
[Unit]
Description=Xatkit service
Wants=network-online.target
After=network.target network-online.target

[Service]
Environment=XATKIT=/home/user/xatkit-dev/build
ExecStart=/bin/bash -c '${XATKIT}/bin/start-xatkit-linux.sh ${XATKIT}/examples/GreetingsBots/GreetingsBot/GreetingsBot.properties'
Type=simple
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
```

3. Enable the service:
```
sudo systemctl enable xatkit
```

4. Start the service for the first time:
``` 
sudo systemctl start xatkit
```

**Comment by gdaniel** [comment]
Documented in the wiki: https://github.com/xatkit-bot-platform/xatkit/wiki/Installation#deploy-xatkit-as-a-systemd-service-optional
