### ISSUE TITLE
Provide a simple example on how to deploy Xatkit behind a reverse proxy

### ISSUE THREAD

**Issue by abelgomez** [xatkit-bot-platform/xatkit-dev#13]
Suggestion: it may be a good idea to provide some simple instructions on how to deploy the example _GreetingsBot_ behind a reverse proxy. Using a reverse proxy greatly simplifies some stuff, like enabling HTTPS.

A possibility would be to deploy Xatkit behing nginx. If we use a Debian-based Linux distribution (as Ubuntu, which it is said the only Linux distribution supported at the moment), the steps would be:

1. Install nginx:
```
sudo apt install nginx
```

2. Disable the default config:
```
sudo rm /etc/nginx/sites-enabled/default
```

3. Create a new configuration, for example using nano:
```
sudo nano /etc/nginx/sites-available/xatkit.conf
```

4. Set a (very basic!) configuration for the proxy:
```
server {

  listen 80 default_server;

  location /admin {
    proxy_pass http://localhost:5000/admin;

    sub_filter "http://localhost:5001" "http://$host";
    sub_filter_once off;
  }

  location /socket.io {
    proxy_pass http://localhost:5001/socket.io;
  }
}
```

5. Enable the new configuration:
```
ln -s /etc/nginx/sites-available/xatkit.conf /etc/nginx/sites-enabled/xatkit.conf
```

6. Restart nginx:
```
sudo systemctl restart nginx
```

At this point, Xatkit should be available directly in http://your-public-hostname. From this point on, the user can follow the instructions in `https://certbot.eff.org/instructions` to enable HTTPS.

Other more complex setups are possible (e.g., Xatkit behind a proxy and with NAT, etc.).

**Comment by gdaniel** [comment]
Reused your instructions in [this wiki article](https://github.com/xatkit-bot-platform/xatkit/wiki/Deploy-a-Xatkit-bot-behind-a-reverse-proxy), thanks!

**Comment by abelgomez** [comment]
Thanks! Just one comment. Although the instructions can be understood by anybody with some Linux experience, they refer to Debian-based systems since the "sites-enabled" and "sites-available" directories are a convention of Debian :)

Maybe this should be specified somewhere in the wiki :)

**Comment by gdaniel** [comment]
Ok, I'll add a note about it in the wiki, thanks :)

Le lun. 4 mai 2020 à 1:24 PM, Abel Gómez <notifications@github.com> a
écrit :
