### ISSUE TITLE
Update Requirements in README.md

### ISSUE THREAD

**Issue by abelgomez** [xatkit-bot-platform/xatkit-dev#14]
It should be explicitly said that `unzip` is required to run the `build.sh` bash script in the _Requirements_ section of README.md. `unzip` isn't normally part of a bare minimum Linux installation. If `unzip`is not present, the build process will fail silently.

Whether if a command is available or not, can be tested using `command -v <command>`. The `$?` will be != 0 if the command is not present. Consider using it for other requirements (e.g., `git`, `mvn`, ...)

**Comment by gdaniel** [comment]
Fixed in 9484ec245a6b5009ff38106fc132ed09f1324d59
