### ISSUE TITLE
rm error when building product for the first time

### ISSUE THREAD

**Issue by gdaniel** [xatkit-bot-platform/xatkit-dev#8]
The `rm` command prints a warning because it cannot remove the `xatkit-nodep-jar-with-dependencies.jar` file from the build folder (it doesn't exist, which is normal).

We should add a test in the `build.sh` script to check if the file exists before deleting it.

**Comment by abelgomez** [comment]
Running `rm -f` instead of a plain `rm` does not print any error message. Addressed in #11

**Comment by gdaniel** [comment]
fixed in #11
